### PR TITLE
Add rudimentary EOF checks

### PR DESCRIPTION
**Pull request by TheLoneWolfling**
Not exactly the _nicest_ way to do this, but it at least prevents a segfault (and provides a starting point for later).

### CODE REVIEW

**Comment by incrediblesound** [comment]
Could you explain why some of the functions terminate with exit(1) and some with exit(0)? Shouldn't they all be exit(0)?

**Comment by TheLoneWolfling** [comment]
...Because I changed them and missed some. I'll update it.

Personally, syntax errors (as in "this script is invalid") should be a failure return code (i.e. non-zero). For instance, python3 -c "abcd" gives a return code of 1. So they should all be non-zero.

**Comment by TheLoneWolfling** [comment]
That better?

**Comment by TheLoneWolfling** [comment]
(Just keeping this branch up to date with master)

**Comment by incrediblesound** [comment]
Nice! The error Macro is slightly hacky, but I think that's fine because it's just a convenience for printing errors and cleans up the rest of the code as well.

**Comment by TheLoneWolfling** [comment]
"Slightly", you say. It's certainly something that should be replaced somewhere down the line, that's for sure.

**Pull request merged**
