### PR TITLE
Revamp parser

### PR DESCRIPTION
**Pull request by TheLoneWolfling**
Current problems:
1. true / false don't work.
2. ?

### CODE REVIEW

**Comment by incrediblesound** [comment]
Weird, I was using them quite a bit, how were you using them such that they didn't work?

**Comment by TheLoneWolfling** [comment]
On second thought, this is rather borked:

```
:huo:> 1
1
:huo:> (+ 1 1)
1
:huo:> a
1
:huo:> sd
1
:huo:> g
1
```

**Comment by TheLoneWolfling** [comment]
Well, I fixed the borkiness at least.

As for "how were you using them such that they didn't work?", this branch doesn't have true / false as keywords or anything similar at the moment.

I think I misphrased my "what doesn't work" statement. That is "what doesn't work _on this branch"_, not "what is fixed on this branch".

Except that true/false are now fixed.

**Comment by incrediblesound** [comment]
Ah OK I understand now, I will merge it in tonight or tomorrow morning and do some testing.

**Pull request merged**
